//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteHospitalSWNet.ServicioEnfermedadSW {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://serviciosWeb/", ConfigurationName="ServicioEnfermedadSW.ServicioEnfermedadSW")]
    public interface ServicioEnfermedadSW {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioEnfermedadSW/listarEnfermedadesRequest", ReplyAction="http://serviciosWeb/ServicioEnfermedadSW/listarEnfermedadesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarEnfermedades))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarEnfermedadResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarEnfermedad))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteHospitalSWNet.ServicioEnfermedadSW.listarEnfermedadesResponse listarEnfermedades(ClienteHospitalSWNet.ServicioEnfermedadSW.listarEnfermedadesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioEnfermedadSW/listarEnfermedadesRequest", ReplyAction="http://serviciosWeb/ServicioEnfermedadSW/listarEnfermedadesResponse")]
        System.Threading.Tasks.Task<ClienteHospitalSWNet.ServicioEnfermedadSW.listarEnfermedadesResponse> listarEnfermedadesAsync(ClienteHospitalSWNet.ServicioEnfermedadSW.listarEnfermedadesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioEnfermedadSW/agregarEnfermedadRequest", ReplyAction="http://serviciosWeb/ServicioEnfermedadSW/agregarEnfermedadResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarEnfermedades))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarEnfermedadResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarEnfermedad))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteHospitalSWNet.ServicioEnfermedadSW.agregarEnfermedadResponse1 agregarEnfermedad(ClienteHospitalSWNet.ServicioEnfermedadSW.agregarEnfermedadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioEnfermedadSW/agregarEnfermedadRequest", ReplyAction="http://serviciosWeb/ServicioEnfermedadSW/agregarEnfermedadResponse")]
        System.Threading.Tasks.Task<ClienteHospitalSWNet.ServicioEnfermedadSW.agregarEnfermedadResponse1> agregarEnfermedadAsync(ClienteHospitalSWNet.ServicioEnfermedadSW.agregarEnfermedadRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class listarEnfermedades : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class agregarEnfermedadResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class enfermedad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private string nombreField;
        
        private string tipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class agregarEnfermedad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private enfermedad arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public enfermedad arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEnfermedades", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class listarEnfermedadesRequest {
        
        public listarEnfermedadesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEnfermedadesResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class listarEnfermedadesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] @return;
        
        public listarEnfermedadesResponse() {
        }
        
        public listarEnfermedadesResponse(object[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregarEnfermedad", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class agregarEnfermedadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteHospitalSWNet.ServicioEnfermedadSW.enfermedad arg0;
        
        public agregarEnfermedadRequest() {
        }
        
        public agregarEnfermedadRequest(ClienteHospitalSWNet.ServicioEnfermedadSW.enfermedad arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregarEnfermedadResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class agregarEnfermedadResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public agregarEnfermedadResponse1() {
        }
        
        public agregarEnfermedadResponse1(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioEnfermedadSWChannel : ClienteHospitalSWNet.ServicioEnfermedadSW.ServicioEnfermedadSW, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioEnfermedadSWClient : System.ServiceModel.ClientBase<ClienteHospitalSWNet.ServicioEnfermedadSW.ServicioEnfermedadSW>, ClienteHospitalSWNet.ServicioEnfermedadSW.ServicioEnfermedadSW {
        
        public ServicioEnfermedadSWClient() {
        }
        
        public ServicioEnfermedadSWClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioEnfermedadSWClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEnfermedadSWClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEnfermedadSWClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteHospitalSWNet.ServicioEnfermedadSW.listarEnfermedadesResponse ClienteHospitalSWNet.ServicioEnfermedadSW.ServicioEnfermedadSW.listarEnfermedades(ClienteHospitalSWNet.ServicioEnfermedadSW.listarEnfermedadesRequest request) {
            return base.Channel.listarEnfermedades(request);
        }
        
        public object[] listarEnfermedades() {
            ClienteHospitalSWNet.ServicioEnfermedadSW.listarEnfermedadesRequest inValue = new ClienteHospitalSWNet.ServicioEnfermedadSW.listarEnfermedadesRequest();
            ClienteHospitalSWNet.ServicioEnfermedadSW.listarEnfermedadesResponse retVal = ((ClienteHospitalSWNet.ServicioEnfermedadSW.ServicioEnfermedadSW)(this)).listarEnfermedades(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteHospitalSWNet.ServicioEnfermedadSW.listarEnfermedadesResponse> ClienteHospitalSWNet.ServicioEnfermedadSW.ServicioEnfermedadSW.listarEnfermedadesAsync(ClienteHospitalSWNet.ServicioEnfermedadSW.listarEnfermedadesRequest request) {
            return base.Channel.listarEnfermedadesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteHospitalSWNet.ServicioEnfermedadSW.listarEnfermedadesResponse> listarEnfermedadesAsync() {
            ClienteHospitalSWNet.ServicioEnfermedadSW.listarEnfermedadesRequest inValue = new ClienteHospitalSWNet.ServicioEnfermedadSW.listarEnfermedadesRequest();
            return ((ClienteHospitalSWNet.ServicioEnfermedadSW.ServicioEnfermedadSW)(this)).listarEnfermedadesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteHospitalSWNet.ServicioEnfermedadSW.agregarEnfermedadResponse1 ClienteHospitalSWNet.ServicioEnfermedadSW.ServicioEnfermedadSW.agregarEnfermedad(ClienteHospitalSWNet.ServicioEnfermedadSW.agregarEnfermedadRequest request) {
            return base.Channel.agregarEnfermedad(request);
        }
        
        public int agregarEnfermedad(ClienteHospitalSWNet.ServicioEnfermedadSW.enfermedad arg0) {
            ClienteHospitalSWNet.ServicioEnfermedadSW.agregarEnfermedadRequest inValue = new ClienteHospitalSWNet.ServicioEnfermedadSW.agregarEnfermedadRequest();
            inValue.arg0 = arg0;
            ClienteHospitalSWNet.ServicioEnfermedadSW.agregarEnfermedadResponse1 retVal = ((ClienteHospitalSWNet.ServicioEnfermedadSW.ServicioEnfermedadSW)(this)).agregarEnfermedad(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteHospitalSWNet.ServicioEnfermedadSW.agregarEnfermedadResponse1> ClienteHospitalSWNet.ServicioEnfermedadSW.ServicioEnfermedadSW.agregarEnfermedadAsync(ClienteHospitalSWNet.ServicioEnfermedadSW.agregarEnfermedadRequest request) {
            return base.Channel.agregarEnfermedadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteHospitalSWNet.ServicioEnfermedadSW.agregarEnfermedadResponse1> agregarEnfermedadAsync(ClienteHospitalSWNet.ServicioEnfermedadSW.enfermedad arg0) {
            ClienteHospitalSWNet.ServicioEnfermedadSW.agregarEnfermedadRequest inValue = new ClienteHospitalSWNet.ServicioEnfermedadSW.agregarEnfermedadRequest();
            inValue.arg0 = arg0;
            return ((ClienteHospitalSWNet.ServicioEnfermedadSW.ServicioEnfermedadSW)(this)).agregarEnfermedadAsync(inValue);
        }
    }
}
