//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteHospitalSWNet.ServicioHistorialClinicoSW {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://serviciosWeb/", ConfigurationName="ServicioHistorialClinicoSW.HistorialClinicoSW")]
    public interface HistorialClinicoSW {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/HistorialClinicoSW/buscarHistorialSoloRequest", ReplyAction="http://serviciosWeb/HistorialClinicoSW/buscarHistorialSoloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(modificarHistorialResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(modificarHistorial))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarHistorialPorParametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarHistorial))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminarHistorial))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHistorialSoloResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHistorialSolo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHistorialResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHistorial))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarHistorialResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarHistorial))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteHospitalSWNet.ServicioHistorialClinicoSW.buscarHistorialSoloResponse1 buscarHistorialSolo(ClienteHospitalSWNet.ServicioHistorialClinicoSW.buscarHistorialSoloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/HistorialClinicoSW/buscarHistorialSoloRequest", ReplyAction="http://serviciosWeb/HistorialClinicoSW/buscarHistorialSoloResponse")]
        System.Threading.Tasks.Task<ClienteHospitalSWNet.ServicioHistorialClinicoSW.buscarHistorialSoloResponse1> buscarHistorialSoloAsync(ClienteHospitalSWNet.ServicioHistorialClinicoSW.buscarHistorialSoloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/HistorialClinicoSW/listarHistorialPorParametroRequest", ReplyAction="http://serviciosWeb/HistorialClinicoSW/listarHistorialPorParametroResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(modificarHistorialResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(modificarHistorial))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarHistorialPorParametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarHistorial))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminarHistorial))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHistorialSoloResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHistorialSolo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHistorialResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHistorial))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarHistorialResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarHistorial))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteHospitalSWNet.ServicioHistorialClinicoSW.listarHistorialPorParametroResponse listarHistorialPorParametro(ClienteHospitalSWNet.ServicioHistorialClinicoSW.listarHistorialPorParametroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/HistorialClinicoSW/listarHistorialPorParametroRequest", ReplyAction="http://serviciosWeb/HistorialClinicoSW/listarHistorialPorParametroResponse")]
        System.Threading.Tasks.Task<ClienteHospitalSWNet.ServicioHistorialClinicoSW.listarHistorialPorParametroResponse> listarHistorialPorParametroAsync(ClienteHospitalSWNet.ServicioHistorialClinicoSW.listarHistorialPorParametroRequest request);
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://serviciosWeb/HistorialClinicoSW/eliminarHistorial")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(modificarHistorialResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(modificarHistorial))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarHistorialPorParametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarHistorial))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminarHistorial))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHistorialSoloResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHistorialSolo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHistorialResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHistorial))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarHistorialResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarHistorial))]
        void eliminarHistorial(ClienteHospitalSWNet.ServicioHistorialClinicoSW.eliminarHistorial1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://serviciosWeb/HistorialClinicoSW/eliminarHistorial")]
        System.Threading.Tasks.Task eliminarHistorialAsync(ClienteHospitalSWNet.ServicioHistorialClinicoSW.eliminarHistorial1 request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/HistorialClinicoSW/modificarHistorialRequest", ReplyAction="http://serviciosWeb/HistorialClinicoSW/modificarHistorialResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(modificarHistorialResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(modificarHistorial))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarHistorialPorParametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarHistorial))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminarHistorial))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHistorialSoloResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHistorialSolo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHistorialResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHistorial))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarHistorialResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarHistorial))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteHospitalSWNet.ServicioHistorialClinicoSW.modificarHistorialResponse1 modificarHistorial(ClienteHospitalSWNet.ServicioHistorialClinicoSW.modificarHistorialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/HistorialClinicoSW/modificarHistorialRequest", ReplyAction="http://serviciosWeb/HistorialClinicoSW/modificarHistorialResponse")]
        System.Threading.Tasks.Task<ClienteHospitalSWNet.ServicioHistorialClinicoSW.modificarHistorialResponse1> modificarHistorialAsync(ClienteHospitalSWNet.ServicioHistorialClinicoSW.modificarHistorialRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/HistorialClinicoSW/listarHistorialRequest", ReplyAction="http://serviciosWeb/HistorialClinicoSW/listarHistorialResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(modificarHistorialResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(modificarHistorial))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarHistorialPorParametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarHistorial))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminarHistorial))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHistorialSoloResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHistorialSolo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHistorialResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHistorial))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarHistorialResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarHistorial))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteHospitalSWNet.ServicioHistorialClinicoSW.listarHistorialResponse listarHistorial(ClienteHospitalSWNet.ServicioHistorialClinicoSW.listarHistorialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/HistorialClinicoSW/listarHistorialRequest", ReplyAction="http://serviciosWeb/HistorialClinicoSW/listarHistorialResponse")]
        System.Threading.Tasks.Task<ClienteHospitalSWNet.ServicioHistorialClinicoSW.listarHistorialResponse> listarHistorialAsync(ClienteHospitalSWNet.ServicioHistorialClinicoSW.listarHistorialRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/HistorialClinicoSW/agregarHistorialRequest", ReplyAction="http://serviciosWeb/HistorialClinicoSW/agregarHistorialResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(modificarHistorialResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(modificarHistorial))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarHistorialPorParametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarHistorial))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminarHistorial))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHistorialSoloResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHistorialSolo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHistorialResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHistorial))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarHistorialResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarHistorial))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteHospitalSWNet.ServicioHistorialClinicoSW.agregarHistorialResponse1 agregarHistorial(ClienteHospitalSWNet.ServicioHistorialClinicoSW.agregarHistorialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/HistorialClinicoSW/agregarHistorialRequest", ReplyAction="http://serviciosWeb/HistorialClinicoSW/agregarHistorialResponse")]
        System.Threading.Tasks.Task<ClienteHospitalSWNet.ServicioHistorialClinicoSW.agregarHistorialResponse1> agregarHistorialAsync(ClienteHospitalSWNet.ServicioHistorialClinicoSW.agregarHistorialRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/HistorialClinicoSW/buscarHistorialRequest", ReplyAction="http://serviciosWeb/HistorialClinicoSW/buscarHistorialResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(modificarHistorialResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(modificarHistorial))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarHistorialPorParametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarHistorial))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminarHistorial))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHistorialSoloResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHistorialSolo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHistorialResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarHistorial))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarHistorialResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarHistorial))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteHospitalSWNet.ServicioHistorialClinicoSW.buscarHistorialResponse1 buscarHistorial(ClienteHospitalSWNet.ServicioHistorialClinicoSW.buscarHistorialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/HistorialClinicoSW/buscarHistorialRequest", ReplyAction="http://serviciosWeb/HistorialClinicoSW/buscarHistorialResponse")]
        System.Threading.Tasks.Task<ClienteHospitalSWNet.ServicioHistorialClinicoSW.buscarHistorialResponse1> buscarHistorialAsync(ClienteHospitalSWNet.ServicioHistorialClinicoSW.buscarHistorialRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class historialClinico : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private int fk_enfermedadField;
        
        private string fk_pacienteField;
        
        private string nombreDoctorField;
        
        private int numeroHistoriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int fk_enfermedad {
            get {
                return this.fk_enfermedadField;
            }
            set {
                this.fk_enfermedadField = value;
                this.RaisePropertyChanged("fk_enfermedad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string fk_paciente {
            get {
                return this.fk_pacienteField;
            }
            set {
                this.fk_pacienteField = value;
                this.RaisePropertyChanged("fk_paciente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombreDoctor {
            get {
                return this.nombreDoctorField;
            }
            set {
                this.nombreDoctorField = value;
                this.RaisePropertyChanged("nombreDoctor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int numeroHistoria {
            get {
                return this.numeroHistoriaField;
            }
            set {
                this.numeroHistoriaField = value;
                this.RaisePropertyChanged("numeroHistoria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class modificarHistorialResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class modificarHistorial : object, System.ComponentModel.INotifyPropertyChanged {
        
        private historialClinico arg0Field;
        
        private int arg1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public historialClinico arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
                this.RaisePropertyChanged("arg1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class listarHistorialPorParametro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class listarHistorial : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class eliminarHistorial : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class buscarHistorialSoloResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private historialClinico returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public historialClinico @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class buscarHistorialSolo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class buscarHistorialResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private historialClinico returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public historialClinico @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class buscarHistorial : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int arg0Field;
        
        private string arg1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
                this.RaisePropertyChanged("arg1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class agregarHistorialResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class agregarHistorial : object, System.ComponentModel.INotifyPropertyChanged {
        
        private historialClinico arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public historialClinico arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarHistorialSolo", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class buscarHistorialSoloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public buscarHistorialSoloRequest() {
        }
        
        public buscarHistorialSoloRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarHistorialSoloResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class buscarHistorialSoloResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteHospitalSWNet.ServicioHistorialClinicoSW.historialClinico @return;
        
        public buscarHistorialSoloResponse1() {
        }
        
        public buscarHistorialSoloResponse1(ClienteHospitalSWNet.ServicioHistorialClinicoSW.historialClinico @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarHistorialPorParametro", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class listarHistorialPorParametroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public listarHistorialPorParametroRequest() {
        }
        
        public listarHistorialPorParametroRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarHistorialPorParametroResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class listarHistorialPorParametroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] @return;
        
        public listarHistorialPorParametroResponse() {
        }
        
        public listarHistorialPorParametroResponse(object[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarHistorial", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class eliminarHistorial1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public eliminarHistorial1() {
        }
        
        public eliminarHistorial1(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarHistorial", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class modificarHistorialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteHospitalSWNet.ServicioHistorialClinicoSW.historialClinico arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public modificarHistorialRequest() {
        }
        
        public modificarHistorialRequest(ClienteHospitalSWNet.ServicioHistorialClinicoSW.historialClinico arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarHistorialResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class modificarHistorialResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarHistorialResponse1() {
        }
        
        public modificarHistorialResponse1(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarHistorial", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class listarHistorialRequest {
        
        public listarHistorialRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarHistorialResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class listarHistorialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] @return;
        
        public listarHistorialResponse() {
        }
        
        public listarHistorialResponse(object[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregarHistorial", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class agregarHistorialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteHospitalSWNet.ServicioHistorialClinicoSW.historialClinico arg0;
        
        public agregarHistorialRequest() {
        }
        
        public agregarHistorialRequest(ClienteHospitalSWNet.ServicioHistorialClinicoSW.historialClinico arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregarHistorialResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class agregarHistorialResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public agregarHistorialResponse1() {
        }
        
        public agregarHistorialResponse1(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarHistorial", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class buscarHistorialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public buscarHistorialRequest() {
        }
        
        public buscarHistorialRequest(int arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarHistorialResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class buscarHistorialResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteHospitalSWNet.ServicioHistorialClinicoSW.historialClinico @return;
        
        public buscarHistorialResponse1() {
        }
        
        public buscarHistorialResponse1(ClienteHospitalSWNet.ServicioHistorialClinicoSW.historialClinico @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HistorialClinicoSWChannel : ClienteHospitalSWNet.ServicioHistorialClinicoSW.HistorialClinicoSW, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HistorialClinicoSWClient : System.ServiceModel.ClientBase<ClienteHospitalSWNet.ServicioHistorialClinicoSW.HistorialClinicoSW>, ClienteHospitalSWNet.ServicioHistorialClinicoSW.HistorialClinicoSW {
        
        public HistorialClinicoSWClient() {
        }
        
        public HistorialClinicoSWClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HistorialClinicoSWClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HistorialClinicoSWClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HistorialClinicoSWClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteHospitalSWNet.ServicioHistorialClinicoSW.buscarHistorialSoloResponse1 ClienteHospitalSWNet.ServicioHistorialClinicoSW.HistorialClinicoSW.buscarHistorialSolo(ClienteHospitalSWNet.ServicioHistorialClinicoSW.buscarHistorialSoloRequest request) {
            return base.Channel.buscarHistorialSolo(request);
        }
        
        public ClienteHospitalSWNet.ServicioHistorialClinicoSW.historialClinico buscarHistorialSolo(int arg0) {
            ClienteHospitalSWNet.ServicioHistorialClinicoSW.buscarHistorialSoloRequest inValue = new ClienteHospitalSWNet.ServicioHistorialClinicoSW.buscarHistorialSoloRequest();
            inValue.arg0 = arg0;
            ClienteHospitalSWNet.ServicioHistorialClinicoSW.buscarHistorialSoloResponse1 retVal = ((ClienteHospitalSWNet.ServicioHistorialClinicoSW.HistorialClinicoSW)(this)).buscarHistorialSolo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteHospitalSWNet.ServicioHistorialClinicoSW.buscarHistorialSoloResponse1> ClienteHospitalSWNet.ServicioHistorialClinicoSW.HistorialClinicoSW.buscarHistorialSoloAsync(ClienteHospitalSWNet.ServicioHistorialClinicoSW.buscarHistorialSoloRequest request) {
            return base.Channel.buscarHistorialSoloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteHospitalSWNet.ServicioHistorialClinicoSW.buscarHistorialSoloResponse1> buscarHistorialSoloAsync(int arg0) {
            ClienteHospitalSWNet.ServicioHistorialClinicoSW.buscarHistorialSoloRequest inValue = new ClienteHospitalSWNet.ServicioHistorialClinicoSW.buscarHistorialSoloRequest();
            inValue.arg0 = arg0;
            return ((ClienteHospitalSWNet.ServicioHistorialClinicoSW.HistorialClinicoSW)(this)).buscarHistorialSoloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteHospitalSWNet.ServicioHistorialClinicoSW.listarHistorialPorParametroResponse ClienteHospitalSWNet.ServicioHistorialClinicoSW.HistorialClinicoSW.listarHistorialPorParametro(ClienteHospitalSWNet.ServicioHistorialClinicoSW.listarHistorialPorParametroRequest request) {
            return base.Channel.listarHistorialPorParametro(request);
        }
        
        public object[] listarHistorialPorParametro(string arg0) {
            ClienteHospitalSWNet.ServicioHistorialClinicoSW.listarHistorialPorParametroRequest inValue = new ClienteHospitalSWNet.ServicioHistorialClinicoSW.listarHistorialPorParametroRequest();
            inValue.arg0 = arg0;
            ClienteHospitalSWNet.ServicioHistorialClinicoSW.listarHistorialPorParametroResponse retVal = ((ClienteHospitalSWNet.ServicioHistorialClinicoSW.HistorialClinicoSW)(this)).listarHistorialPorParametro(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteHospitalSWNet.ServicioHistorialClinicoSW.listarHistorialPorParametroResponse> ClienteHospitalSWNet.ServicioHistorialClinicoSW.HistorialClinicoSW.listarHistorialPorParametroAsync(ClienteHospitalSWNet.ServicioHistorialClinicoSW.listarHistorialPorParametroRequest request) {
            return base.Channel.listarHistorialPorParametroAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteHospitalSWNet.ServicioHistorialClinicoSW.listarHistorialPorParametroResponse> listarHistorialPorParametroAsync(string arg0) {
            ClienteHospitalSWNet.ServicioHistorialClinicoSW.listarHistorialPorParametroRequest inValue = new ClienteHospitalSWNet.ServicioHistorialClinicoSW.listarHistorialPorParametroRequest();
            inValue.arg0 = arg0;
            return ((ClienteHospitalSWNet.ServicioHistorialClinicoSW.HistorialClinicoSW)(this)).listarHistorialPorParametroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ClienteHospitalSWNet.ServicioHistorialClinicoSW.HistorialClinicoSW.eliminarHistorial(ClienteHospitalSWNet.ServicioHistorialClinicoSW.eliminarHistorial1 request) {
            base.Channel.eliminarHistorial(request);
        }
        
        public void eliminarHistorial(int arg0) {
            ClienteHospitalSWNet.ServicioHistorialClinicoSW.eliminarHistorial1 inValue = new ClienteHospitalSWNet.ServicioHistorialClinicoSW.eliminarHistorial1();
            inValue.arg0 = arg0;
            ((ClienteHospitalSWNet.ServicioHistorialClinicoSW.HistorialClinicoSW)(this)).eliminarHistorial(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task ClienteHospitalSWNet.ServicioHistorialClinicoSW.HistorialClinicoSW.eliminarHistorialAsync(ClienteHospitalSWNet.ServicioHistorialClinicoSW.eliminarHistorial1 request) {
            return base.Channel.eliminarHistorialAsync(request);
        }
        
        public System.Threading.Tasks.Task eliminarHistorialAsync(int arg0) {
            ClienteHospitalSWNet.ServicioHistorialClinicoSW.eliminarHistorial1 inValue = new ClienteHospitalSWNet.ServicioHistorialClinicoSW.eliminarHistorial1();
            inValue.arg0 = arg0;
            return ((ClienteHospitalSWNet.ServicioHistorialClinicoSW.HistorialClinicoSW)(this)).eliminarHistorialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteHospitalSWNet.ServicioHistorialClinicoSW.modificarHistorialResponse1 ClienteHospitalSWNet.ServicioHistorialClinicoSW.HistorialClinicoSW.modificarHistorial(ClienteHospitalSWNet.ServicioHistorialClinicoSW.modificarHistorialRequest request) {
            return base.Channel.modificarHistorial(request);
        }
        
        public int modificarHistorial(ClienteHospitalSWNet.ServicioHistorialClinicoSW.historialClinico arg0, int arg1) {
            ClienteHospitalSWNet.ServicioHistorialClinicoSW.modificarHistorialRequest inValue = new ClienteHospitalSWNet.ServicioHistorialClinicoSW.modificarHistorialRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            ClienteHospitalSWNet.ServicioHistorialClinicoSW.modificarHistorialResponse1 retVal = ((ClienteHospitalSWNet.ServicioHistorialClinicoSW.HistorialClinicoSW)(this)).modificarHistorial(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteHospitalSWNet.ServicioHistorialClinicoSW.modificarHistorialResponse1> ClienteHospitalSWNet.ServicioHistorialClinicoSW.HistorialClinicoSW.modificarHistorialAsync(ClienteHospitalSWNet.ServicioHistorialClinicoSW.modificarHistorialRequest request) {
            return base.Channel.modificarHistorialAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteHospitalSWNet.ServicioHistorialClinicoSW.modificarHistorialResponse1> modificarHistorialAsync(ClienteHospitalSWNet.ServicioHistorialClinicoSW.historialClinico arg0, int arg1) {
            ClienteHospitalSWNet.ServicioHistorialClinicoSW.modificarHistorialRequest inValue = new ClienteHospitalSWNet.ServicioHistorialClinicoSW.modificarHistorialRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ClienteHospitalSWNet.ServicioHistorialClinicoSW.HistorialClinicoSW)(this)).modificarHistorialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteHospitalSWNet.ServicioHistorialClinicoSW.listarHistorialResponse ClienteHospitalSWNet.ServicioHistorialClinicoSW.HistorialClinicoSW.listarHistorial(ClienteHospitalSWNet.ServicioHistorialClinicoSW.listarHistorialRequest request) {
            return base.Channel.listarHistorial(request);
        }
        
        public object[] listarHistorial() {
            ClienteHospitalSWNet.ServicioHistorialClinicoSW.listarHistorialRequest inValue = new ClienteHospitalSWNet.ServicioHistorialClinicoSW.listarHistorialRequest();
            ClienteHospitalSWNet.ServicioHistorialClinicoSW.listarHistorialResponse retVal = ((ClienteHospitalSWNet.ServicioHistorialClinicoSW.HistorialClinicoSW)(this)).listarHistorial(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteHospitalSWNet.ServicioHistorialClinicoSW.listarHistorialResponse> ClienteHospitalSWNet.ServicioHistorialClinicoSW.HistorialClinicoSW.listarHistorialAsync(ClienteHospitalSWNet.ServicioHistorialClinicoSW.listarHistorialRequest request) {
            return base.Channel.listarHistorialAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteHospitalSWNet.ServicioHistorialClinicoSW.listarHistorialResponse> listarHistorialAsync() {
            ClienteHospitalSWNet.ServicioHistorialClinicoSW.listarHistorialRequest inValue = new ClienteHospitalSWNet.ServicioHistorialClinicoSW.listarHistorialRequest();
            return ((ClienteHospitalSWNet.ServicioHistorialClinicoSW.HistorialClinicoSW)(this)).listarHistorialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteHospitalSWNet.ServicioHistorialClinicoSW.agregarHistorialResponse1 ClienteHospitalSWNet.ServicioHistorialClinicoSW.HistorialClinicoSW.agregarHistorial(ClienteHospitalSWNet.ServicioHistorialClinicoSW.agregarHistorialRequest request) {
            return base.Channel.agregarHistorial(request);
        }
        
        public int agregarHistorial(ClienteHospitalSWNet.ServicioHistorialClinicoSW.historialClinico arg0) {
            ClienteHospitalSWNet.ServicioHistorialClinicoSW.agregarHistorialRequest inValue = new ClienteHospitalSWNet.ServicioHistorialClinicoSW.agregarHistorialRequest();
            inValue.arg0 = arg0;
            ClienteHospitalSWNet.ServicioHistorialClinicoSW.agregarHistorialResponse1 retVal = ((ClienteHospitalSWNet.ServicioHistorialClinicoSW.HistorialClinicoSW)(this)).agregarHistorial(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteHospitalSWNet.ServicioHistorialClinicoSW.agregarHistorialResponse1> ClienteHospitalSWNet.ServicioHistorialClinicoSW.HistorialClinicoSW.agregarHistorialAsync(ClienteHospitalSWNet.ServicioHistorialClinicoSW.agregarHistorialRequest request) {
            return base.Channel.agregarHistorialAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteHospitalSWNet.ServicioHistorialClinicoSW.agregarHistorialResponse1> agregarHistorialAsync(ClienteHospitalSWNet.ServicioHistorialClinicoSW.historialClinico arg0) {
            ClienteHospitalSWNet.ServicioHistorialClinicoSW.agregarHistorialRequest inValue = new ClienteHospitalSWNet.ServicioHistorialClinicoSW.agregarHistorialRequest();
            inValue.arg0 = arg0;
            return ((ClienteHospitalSWNet.ServicioHistorialClinicoSW.HistorialClinicoSW)(this)).agregarHistorialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteHospitalSWNet.ServicioHistorialClinicoSW.buscarHistorialResponse1 ClienteHospitalSWNet.ServicioHistorialClinicoSW.HistorialClinicoSW.buscarHistorial(ClienteHospitalSWNet.ServicioHistorialClinicoSW.buscarHistorialRequest request) {
            return base.Channel.buscarHistorial(request);
        }
        
        public ClienteHospitalSWNet.ServicioHistorialClinicoSW.historialClinico buscarHistorial(int arg0, string arg1) {
            ClienteHospitalSWNet.ServicioHistorialClinicoSW.buscarHistorialRequest inValue = new ClienteHospitalSWNet.ServicioHistorialClinicoSW.buscarHistorialRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            ClienteHospitalSWNet.ServicioHistorialClinicoSW.buscarHistorialResponse1 retVal = ((ClienteHospitalSWNet.ServicioHistorialClinicoSW.HistorialClinicoSW)(this)).buscarHistorial(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteHospitalSWNet.ServicioHistorialClinicoSW.buscarHistorialResponse1> ClienteHospitalSWNet.ServicioHistorialClinicoSW.HistorialClinicoSW.buscarHistorialAsync(ClienteHospitalSWNet.ServicioHistorialClinicoSW.buscarHistorialRequest request) {
            return base.Channel.buscarHistorialAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteHospitalSWNet.ServicioHistorialClinicoSW.buscarHistorialResponse1> buscarHistorialAsync(int arg0, string arg1) {
            ClienteHospitalSWNet.ServicioHistorialClinicoSW.buscarHistorialRequest inValue = new ClienteHospitalSWNet.ServicioHistorialClinicoSW.buscarHistorialRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ClienteHospitalSWNet.ServicioHistorialClinicoSW.HistorialClinicoSW)(this)).buscarHistorialAsync(inValue);
        }
    }
}
