//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteHospitalSWNet.ServidorPacienteSW {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://serviciosWeb/", ConfigurationName="ServidorPacienteSW.PacienteSW")]
    public interface PacienteSW {
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://serviciosWeb/PacienteSW/eliminarPaciente")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarPaciente(ClienteHospitalSWNet.ServidorPacienteSW.eliminarPaciente request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://serviciosWeb/PacienteSW/eliminarPaciente")]
        System.Threading.Tasks.Task eliminarPacienteAsync(ClienteHospitalSWNet.ServidorPacienteSW.eliminarPaciente request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/PacienteSW/buscarPacienteRequest", ReplyAction="http://serviciosWeb/PacienteSW/buscarPacienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(modificarPacienteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(modificarPaciente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarPorParametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listar))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminarPaciente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPacienteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPaciente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarPacienteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarPaciente))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteHospitalSWNet.ServidorPacienteSW.buscarPacienteResponse1 buscarPaciente(ClienteHospitalSWNet.ServidorPacienteSW.buscarPacienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/PacienteSW/buscarPacienteRequest", ReplyAction="http://serviciosWeb/PacienteSW/buscarPacienteResponse")]
        System.Threading.Tasks.Task<ClienteHospitalSWNet.ServidorPacienteSW.buscarPacienteResponse1> buscarPacienteAsync(ClienteHospitalSWNet.ServidorPacienteSW.buscarPacienteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/PacienteSW/listarRequest", ReplyAction="http://serviciosWeb/PacienteSW/listarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(modificarPacienteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(modificarPaciente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarPorParametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listar))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminarPaciente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPacienteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPaciente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarPacienteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarPaciente))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteHospitalSWNet.ServidorPacienteSW.listarResponse listar(ClienteHospitalSWNet.ServidorPacienteSW.listarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/PacienteSW/listarRequest", ReplyAction="http://serviciosWeb/PacienteSW/listarResponse")]
        System.Threading.Tasks.Task<ClienteHospitalSWNet.ServidorPacienteSW.listarResponse> listarAsync(ClienteHospitalSWNet.ServidorPacienteSW.listarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/PacienteSW/modificarPacienteRequest", ReplyAction="http://serviciosWeb/PacienteSW/modificarPacienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(modificarPacienteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(modificarPaciente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarPorParametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listar))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminarPaciente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPacienteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPaciente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarPacienteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarPaciente))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteHospitalSWNet.ServidorPacienteSW.modificarPacienteResponse1 modificarPaciente(ClienteHospitalSWNet.ServidorPacienteSW.modificarPacienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/PacienteSW/modificarPacienteRequest", ReplyAction="http://serviciosWeb/PacienteSW/modificarPacienteResponse")]
        System.Threading.Tasks.Task<ClienteHospitalSWNet.ServidorPacienteSW.modificarPacienteResponse1> modificarPacienteAsync(ClienteHospitalSWNet.ServidorPacienteSW.modificarPacienteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/PacienteSW/listarPorParametroRequest", ReplyAction="http://serviciosWeb/PacienteSW/listarPorParametroResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(modificarPacienteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(modificarPaciente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarPorParametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listar))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminarPaciente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPacienteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPaciente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarPacienteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarPaciente))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteHospitalSWNet.ServidorPacienteSW.listarPorParametroResponse listarPorParametro(ClienteHospitalSWNet.ServidorPacienteSW.listarPorParametroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/PacienteSW/listarPorParametroRequest", ReplyAction="http://serviciosWeb/PacienteSW/listarPorParametroResponse")]
        System.Threading.Tasks.Task<ClienteHospitalSWNet.ServidorPacienteSW.listarPorParametroResponse> listarPorParametroAsync(ClienteHospitalSWNet.ServidorPacienteSW.listarPorParametroRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/PacienteSW/agregarPacienteRequest", ReplyAction="http://serviciosWeb/PacienteSW/agregarPacienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(modificarPacienteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(modificarPaciente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarPorParametro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listar))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminarPaciente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPacienteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(buscarPaciente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarPacienteResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(agregarPaciente))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteHospitalSWNet.ServidorPacienteSW.agregarPacienteResponse1 agregarPaciente(ClienteHospitalSWNet.ServidorPacienteSW.agregarPacienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/PacienteSW/agregarPacienteRequest", ReplyAction="http://serviciosWeb/PacienteSW/agregarPacienteResponse")]
        System.Threading.Tasks.Task<ClienteHospitalSWNet.ServidorPacienteSW.agregarPacienteResponse1> agregarPacienteAsync(ClienteHospitalSWNet.ServidorPacienteSW.agregarPacienteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPaciente", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class eliminarPaciente {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public eliminarPaciente() {
        }
        
        public eliminarPaciente(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class paciente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string correoField;
        
        private string documentoField;
        
        private string generoField;
        
        private int idField;
        
        private string nombreField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
                this.RaisePropertyChanged("documento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
                this.RaisePropertyChanged("genero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class modificarPacienteResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class modificarPaciente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private paciente arg0Field;
        
        private string arg1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public paciente arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
                this.RaisePropertyChanged("arg1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class listarPorParametro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class listar : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
   
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class buscarPacienteResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private paciente returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public paciente @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class buscarPaciente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class agregarPacienteResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class agregarPaciente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private paciente arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public paciente arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarPaciente", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class buscarPacienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public buscarPacienteRequest() {
        }
        
        public buscarPacienteRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarPacienteResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class buscarPacienteResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteHospitalSWNet.ServidorPacienteSW.paciente @return;
        
        public buscarPacienteResponse1() {
        }
        
        public buscarPacienteResponse1(ClienteHospitalSWNet.ServidorPacienteSW.paciente @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listar", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class listarRequest {
        
        public listarRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class listarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] @return;
        
        public listarResponse() {
        }
        
        public listarResponse(object[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPaciente", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class modificarPacienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteHospitalSWNet.ServidorPacienteSW.paciente arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public modificarPacienteRequest() {
        }
        
        public modificarPacienteRequest(ClienteHospitalSWNet.ServidorPacienteSW.paciente arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPacienteResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class modificarPacienteResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarPacienteResponse1() {
        }
        
        public modificarPacienteResponse1(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorParametro", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class listarPorParametroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public listarPorParametroRequest() {
        }
        
        public listarPorParametroRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorParametroResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class listarPorParametroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] @return;
        
        public listarPorParametroResponse() {
        }
        
        public listarPorParametroResponse(object[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregarPaciente", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class agregarPacienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteHospitalSWNet.ServidorPacienteSW.paciente arg0;
        
        public agregarPacienteRequest() {
        }
        
        public agregarPacienteRequest(ClienteHospitalSWNet.ServidorPacienteSW.paciente arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregarPacienteResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class agregarPacienteResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public agregarPacienteResponse1() {
        }
        
        public agregarPacienteResponse1(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PacienteSWChannel : ClienteHospitalSWNet.ServidorPacienteSW.PacienteSW, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PacienteSWClient : System.ServiceModel.ClientBase<ClienteHospitalSWNet.ServidorPacienteSW.PacienteSW>, ClienteHospitalSWNet.ServidorPacienteSW.PacienteSW {
        
        public PacienteSWClient() {
        }
        
        public PacienteSWClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PacienteSWClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PacienteSWClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PacienteSWClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ClienteHospitalSWNet.ServidorPacienteSW.PacienteSW.eliminarPaciente(ClienteHospitalSWNet.ServidorPacienteSW.eliminarPaciente request) {
            base.Channel.eliminarPaciente(request);
        }
        
        public void eliminarPaciente(string arg0) {
            ClienteHospitalSWNet.ServidorPacienteSW.eliminarPaciente inValue = new ClienteHospitalSWNet.ServidorPacienteSW.eliminarPaciente();
            inValue.arg0 = arg0;
            ((ClienteHospitalSWNet.ServidorPacienteSW.PacienteSW)(this)).eliminarPaciente(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task ClienteHospitalSWNet.ServidorPacienteSW.PacienteSW.eliminarPacienteAsync(ClienteHospitalSWNet.ServidorPacienteSW.eliminarPaciente request) {
            return base.Channel.eliminarPacienteAsync(request);
        }
        
        public System.Threading.Tasks.Task eliminarPacienteAsync(string arg0) {
            ClienteHospitalSWNet.ServidorPacienteSW.eliminarPaciente inValue = new ClienteHospitalSWNet.ServidorPacienteSW.eliminarPaciente();
            inValue.arg0 = arg0;
            return ((ClienteHospitalSWNet.ServidorPacienteSW.PacienteSW)(this)).eliminarPacienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteHospitalSWNet.ServidorPacienteSW.buscarPacienteResponse1 ClienteHospitalSWNet.ServidorPacienteSW.PacienteSW.buscarPaciente(ClienteHospitalSWNet.ServidorPacienteSW.buscarPacienteRequest request) {
            return base.Channel.buscarPaciente(request);
        }
        
        public ClienteHospitalSWNet.ServidorPacienteSW.paciente buscarPaciente(string arg0) {
            ClienteHospitalSWNet.ServidorPacienteSW.buscarPacienteRequest inValue = new ClienteHospitalSWNet.ServidorPacienteSW.buscarPacienteRequest();
            inValue.arg0 = arg0;
            ClienteHospitalSWNet.ServidorPacienteSW.buscarPacienteResponse1 retVal = ((ClienteHospitalSWNet.ServidorPacienteSW.PacienteSW)(this)).buscarPaciente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteHospitalSWNet.ServidorPacienteSW.buscarPacienteResponse1> ClienteHospitalSWNet.ServidorPacienteSW.PacienteSW.buscarPacienteAsync(ClienteHospitalSWNet.ServidorPacienteSW.buscarPacienteRequest request) {
            return base.Channel.buscarPacienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteHospitalSWNet.ServidorPacienteSW.buscarPacienteResponse1> buscarPacienteAsync(string arg0) {
            ClienteHospitalSWNet.ServidorPacienteSW.buscarPacienteRequest inValue = new ClienteHospitalSWNet.ServidorPacienteSW.buscarPacienteRequest();
            inValue.arg0 = arg0;
            return ((ClienteHospitalSWNet.ServidorPacienteSW.PacienteSW)(this)).buscarPacienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteHospitalSWNet.ServidorPacienteSW.listarResponse ClienteHospitalSWNet.ServidorPacienteSW.PacienteSW.listar(ClienteHospitalSWNet.ServidorPacienteSW.listarRequest request) {
            return base.Channel.listar(request);
        }
        
        public object[] listar() {
            ClienteHospitalSWNet.ServidorPacienteSW.listarRequest inValue = new ClienteHospitalSWNet.ServidorPacienteSW.listarRequest();
            ClienteHospitalSWNet.ServidorPacienteSW.listarResponse retVal = ((ClienteHospitalSWNet.ServidorPacienteSW.PacienteSW)(this)).listar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteHospitalSWNet.ServidorPacienteSW.listarResponse> ClienteHospitalSWNet.ServidorPacienteSW.PacienteSW.listarAsync(ClienteHospitalSWNet.ServidorPacienteSW.listarRequest request) {
            return base.Channel.listarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteHospitalSWNet.ServidorPacienteSW.listarResponse> listarAsync() {
            ClienteHospitalSWNet.ServidorPacienteSW.listarRequest inValue = new ClienteHospitalSWNet.ServidorPacienteSW.listarRequest();
            return ((ClienteHospitalSWNet.ServidorPacienteSW.PacienteSW)(this)).listarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteHospitalSWNet.ServidorPacienteSW.modificarPacienteResponse1 ClienteHospitalSWNet.ServidorPacienteSW.PacienteSW.modificarPaciente(ClienteHospitalSWNet.ServidorPacienteSW.modificarPacienteRequest request) {
            return base.Channel.modificarPaciente(request);
        }
        
        public int modificarPaciente(ClienteHospitalSWNet.ServidorPacienteSW.paciente arg0, string arg1) {
            ClienteHospitalSWNet.ServidorPacienteSW.modificarPacienteRequest inValue = new ClienteHospitalSWNet.ServidorPacienteSW.modificarPacienteRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            ClienteHospitalSWNet.ServidorPacienteSW.modificarPacienteResponse1 retVal = ((ClienteHospitalSWNet.ServidorPacienteSW.PacienteSW)(this)).modificarPaciente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteHospitalSWNet.ServidorPacienteSW.modificarPacienteResponse1> ClienteHospitalSWNet.ServidorPacienteSW.PacienteSW.modificarPacienteAsync(ClienteHospitalSWNet.ServidorPacienteSW.modificarPacienteRequest request) {
            return base.Channel.modificarPacienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteHospitalSWNet.ServidorPacienteSW.modificarPacienteResponse1> modificarPacienteAsync(ClienteHospitalSWNet.ServidorPacienteSW.paciente arg0, string arg1) {
            ClienteHospitalSWNet.ServidorPacienteSW.modificarPacienteRequest inValue = new ClienteHospitalSWNet.ServidorPacienteSW.modificarPacienteRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ClienteHospitalSWNet.ServidorPacienteSW.PacienteSW)(this)).modificarPacienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteHospitalSWNet.ServidorPacienteSW.listarPorParametroResponse ClienteHospitalSWNet.ServidorPacienteSW.PacienteSW.listarPorParametro(ClienteHospitalSWNet.ServidorPacienteSW.listarPorParametroRequest request) {
            return base.Channel.listarPorParametro(request);
        }
        
        public object[] listarPorParametro(string arg0) {
            ClienteHospitalSWNet.ServidorPacienteSW.listarPorParametroRequest inValue = new ClienteHospitalSWNet.ServidorPacienteSW.listarPorParametroRequest();
            inValue.arg0 = arg0;
            ClienteHospitalSWNet.ServidorPacienteSW.listarPorParametroResponse retVal = ((ClienteHospitalSWNet.ServidorPacienteSW.PacienteSW)(this)).listarPorParametro(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteHospitalSWNet.ServidorPacienteSW.listarPorParametroResponse> ClienteHospitalSWNet.ServidorPacienteSW.PacienteSW.listarPorParametroAsync(ClienteHospitalSWNet.ServidorPacienteSW.listarPorParametroRequest request) {
            return base.Channel.listarPorParametroAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteHospitalSWNet.ServidorPacienteSW.listarPorParametroResponse> listarPorParametroAsync(string arg0) {
            ClienteHospitalSWNet.ServidorPacienteSW.listarPorParametroRequest inValue = new ClienteHospitalSWNet.ServidorPacienteSW.listarPorParametroRequest();
            inValue.arg0 = arg0;
            return ((ClienteHospitalSWNet.ServidorPacienteSW.PacienteSW)(this)).listarPorParametroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteHospitalSWNet.ServidorPacienteSW.agregarPacienteResponse1 ClienteHospitalSWNet.ServidorPacienteSW.PacienteSW.agregarPaciente(ClienteHospitalSWNet.ServidorPacienteSW.agregarPacienteRequest request) {
            return base.Channel.agregarPaciente(request);
        }
        
        public int agregarPaciente(ClienteHospitalSWNet.ServidorPacienteSW.paciente arg0) {
            ClienteHospitalSWNet.ServidorPacienteSW.agregarPacienteRequest inValue = new ClienteHospitalSWNet.ServidorPacienteSW.agregarPacienteRequest();
            inValue.arg0 = arg0;
            ClienteHospitalSWNet.ServidorPacienteSW.agregarPacienteResponse1 retVal = ((ClienteHospitalSWNet.ServidorPacienteSW.PacienteSW)(this)).agregarPaciente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteHospitalSWNet.ServidorPacienteSW.agregarPacienteResponse1> ClienteHospitalSWNet.ServidorPacienteSW.PacienteSW.agregarPacienteAsync(ClienteHospitalSWNet.ServidorPacienteSW.agregarPacienteRequest request) {
            return base.Channel.agregarPacienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteHospitalSWNet.ServidorPacienteSW.agregarPacienteResponse1> agregarPacienteAsync(ClienteHospitalSWNet.ServidorPacienteSW.paciente arg0) {
            ClienteHospitalSWNet.ServidorPacienteSW.agregarPacienteRequest inValue = new ClienteHospitalSWNet.ServidorPacienteSW.agregarPacienteRequest();
            inValue.arg0 = arg0;
            return ((ClienteHospitalSWNet.ServidorPacienteSW.PacienteSW)(this)).agregarPacienteAsync(inValue);
        }
    }
}
